version: '2'
services:
  octopus:
    container_name: octopus-gateway
    image: amirsoleimani/octopus
    restart: always
    volumes:
       - /Users/xxxx/go/config:/config
    entrypoint:
    - ./octopus
    - --file
    - config
    - --path
    - /config
    - --type
    - file
    ports:
    - "9090:9090"
